version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    command: >-
      bin/spark-class org.apache.spark.deploy.master.Master
    # entrypoint: ["/opt/bitnami/spark/bin/spark-shell","--packages","com.databricks:spark-xml_2.12:0.17.0"]
    ports:
      - 9090:8080
      - 7077:7077
    volumes:
      - ./dump_files:/opt/bitnami/spark/dump_files
    environment:
      SPARK_LOCAL_IP: spark-master
      SPARK_WORKLOAD: master

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077