services:
  nosql_study_api:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_MESSENGER_URI=mongodb://mongo_db:27017
      - ELASTICSEARCH_MESSANGER_URI=http://elasticsearch_db:9200

    depends_on:
      mongo_db:
        condition: service_started
      elasticsearch_db:
        condition: service_healthy

  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  elasticsearch_db:
    image: elasticsearch:8.10.2
    healthcheck:
      interval: 1s
      retries: 60
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elasticsearch_db:9200
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

  kibana:
    image: kibana:8.10.2
    ports:
    - 5601:5601
    volumes:
      - ./data/kibana:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_db:9200
    depends_on:
      elasticsearch_db:
        condition: service_healthy